### PR TITLE
ssh slaves launcher

### PR DESCRIPTION
**Pull request by zhanglianx111**
support ssh slave launcher

### CODE REVIEW

**Comment by zhanglianx111** [comment]
ssh slave launcher

**Comment by zhanglianx111** [comment]
create node test case

**Comment by bndr** [comment]
There are some spelling mistakes, but overall looks good.

**Comment by zhanglianx111** [comment]
thanks! review and give me some suggestions please!


Original Message
Sender:Vadim Kravcenkonotifications@github.com
Recipient:bndr/gojenkinsgojenkins@noreply.github.com
Cc:zhanglianx111zhanglianx111@aliyun.com
Date:Thursday, Nov 12, 2015 16:12
Subject:Re: [gojenkins] ssh slaves launcher (#13)


There are some spelling mistakes, but overall looks good.

**Pull request merged**
