### PR TITLE
fix: check whether the username is "" is needed.

### PR DESCRIPTION
**Pull request by zz-bmj**
- Check whether the username is "" is needed, as we may use Jenkins without any user.

What happened: 

- When I use Jenkins without username and password, it comes the error 401. With the review of code, I found it can create Jenkins Instance successfully, however, when it goes to create a job, it failed.

image

### CODE REVIEW

**Comment by zz-bmj** [comment]
@supereagle @bndr PTAL

**Comment by supereagle** [comment]
If you want to connect Jenkins without username and password, there is no need to pass them. You can use like this:
```go
	jenkins = CreateJenkins(nil, "http://localhost:8080")
	_, err := jenkins.Init()
```

**Comment by zz-bmj** [comment]
@supereagle ok, I know this way to create Jenkins instance, however,  we can not determine which way a user will use in the physical environment. 
    And I don't want to add this check in my code, add this check will be better in my opinion. Or do you have any better suggestion?

**Comment by supereagle** [comment]
The username and password of Jenkins should be read from configuration, so you can new the Jenkins instance according to the configuration. For example:
```go
	jenkins = CreateJenkins(nil, "http://localhost:8080")
	if len(c.Username) != 0 {
		jenkins = CreateJenkins(nil, "http://localhost:8080", c.Username, c.Password)
	}
	_, err := jenkins.Init()
```
`c` is the variable for configuration.

**Comment by zz-bmj** [comment]
ok, I know this way, I just think it not good enough.

**Pull request closed without merging**
